[package]
name = "snake-rust"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "snake_rust"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.27.0"
rand = "0.10.0"
rand_chacha = "0.10.0"
